from __future__ import annotations

from hashlib import sha256
from typing import Iterable

import numpy as np

from ..data.datasets import QueryDataset
from ..kinematics.base import KinematicsModel


OOD_POINT_FAMILIES = (
    "ood_workspace_sector",
    "ood_extreme_singular",
    "ood_extreme_joint_limit",
    "ood_fast_motion",
)
OOD_TRAJECTORY_FAMILIES = (
    "ood_trajectory_high_frequency",
    "ood_trajectory_mixed_curvature",
)


def derive_v4_seed(release_digest: str, robot: str, role: str) -> int:
    material = f"test_v4_locked|{release_digest}|{robot}|{role}".encode("utf-8")
    return int.from_bytes(sha256(material).digest()[:4], "big", signed=False)


def _local_previous(
    kinematics: KinematicsModel,
    target: np.ndarray,
    rng: np.random.Generator,
    *,
    dt: float,
    fraction_low: float,
    fraction_high: float,
) -> np.ndarray:
    direction = rng.normal(size=kinematics.nq)
    direction /= max(float(np.max(np.abs(direction))), 1e-12)
    fraction = float(rng.uniform(fraction_low, fraction_high))
    return kinematics.clip(target - direction * kinematics.limits.velocity * dt * fraction)


def _query_dataset_from_pairs(
    kinematics: KinematicsModel,
    previous: np.ndarray,
    target: np.ndarray,
    *,
    category: str,
    trajectory_offset: int,
) -> QueryDataset:
    poses = [kinematics.forward(q) for q in target]
    count = len(target)
    return QueryDataset(
        previous_q=np.asarray(previous, dtype=np.float64),
        target_position=np.stack([pose.position for pose in poses]),
        target_rotation=np.stack([pose.rotation for pose in poses]),
        reference_q=np.asarray(target, dtype=np.float64),
        category=np.full(count, category),
        expected_reachable=np.ones(count, dtype=bool),
        continuity_feasible=np.ones(count, dtype=bool),
        trajectory_id=np.arange(count, dtype=np.int64) + trajectory_offset,
        time_index=np.zeros(count, dtype=np.int64),
    )


def _workspace_sector_queries(
    kinematics: KinematicsModel,
    *,
    count: int,
    rng: np.random.Generator,
    dt: float,
) -> QueryDataset:
    targets: list[np.ndarray] = []
    previous: list[np.ndarray] = []
    # A rear azimuth sector is held out as a named physical shift.  The target
    # remains known-feasible because it is generated by FK from target_q.
    attempts = 0
    while len(targets) < count and attempts < count * 400:
        attempts += 1
        q = kinematics.random_configuration(rng, margin=0.03)
        pose = kinematics.forward(q)
        azimuth = float(np.arctan2(pose.position[1], pose.position[0]))
        if abs(azimuth) < 2.25:
            continue
        p = _local_previous(
            kinematics,
            q,
            rng,
            dt=dt,
            fraction_low=0.35,
            fraction_high=0.75,
        )
        if np.any(np.abs(kinematics.difference(q, p)) > kinematics.limits.velocity * dt):
            continue
        targets.append(q)
        previous.append(p)
    if len(targets) != count:
        raise RuntimeError(f"generated only {len(targets)}/{count} workspace-sector queries")
    return _query_dataset_from_pairs(
        kinematics,
        np.stack(previous),
        np.stack(targets),
        category="ood_workspace_sector",
        trajectory_offset=410_000_000,
    )


def _extreme_singular_queries(
    kinematics: KinematicsModel,
    *,
    count: int,
    rng: np.random.Generator,
    dt: float,
) -> QueryDataset:
    pool_count = max(count * 30, 512)
    pool = np.stack(
        [kinematics.random_configuration(rng, margin=0.0) for _ in range(pool_count)]
    )
    sigma = np.asarray([kinematics.min_singular_value(q) for q in pool])
    targets = pool[np.argsort(sigma)[:count]]
    previous = np.stack(
        [
            _local_previous(
                kinematics,
                q,
                rng,
                dt=dt,
                fraction_low=0.20,
                fraction_high=0.55,
            )
            for q in targets
        ]
    )
    return _query_dataset_from_pairs(
        kinematics,
        previous,
        targets,
        category="ood_extreme_singular",
        trajectory_offset=420_000_000,
    )


def _extreme_limit_queries(
    kinematics: KinematicsModel,
    *,
    count: int,
    rng: np.random.Generator,
    dt: float,
) -> QueryDataset:
    targets = np.stack(
        [kinematics.random_configuration(rng, margin=0.0) for _ in range(count)]
    )
    span = kinematics.limits.upper - kinematics.limits.lower
    for index, target in enumerate(targets):
        joint = index % kinematics.nq
        epsilon = float(rng.uniform(0.0002, 0.0010)) * span[joint]
        target[joint] = (
            kinematics.limits.lower[joint] + epsilon
            if index % 2 == 0
            else kinematics.limits.upper[joint] - epsilon
        )
    previous = np.stack(
        [
            _local_previous(
                kinematics,
                q,
                rng,
                dt=dt,
                fraction_low=0.15,
                fraction_high=0.45,
            )
            for q in targets
        ]
    )
    return _query_dataset_from_pairs(
        kinematics,
        previous,
        targets,
        category="ood_extreme_joint_limit",
        trajectory_offset=430_000_000,
    )


def _fast_motion_queries(
    kinematics: KinematicsModel,
    *,
    count: int,
    rng: np.random.Generator,
    dt: float,
) -> QueryDataset:
    targets = np.stack(
        [kinematics.random_configuration(rng, margin=0.08) for _ in range(count)]
    )
    previous = np.stack(
        [
            _local_previous(
                kinematics,
                q,
                rng,
                dt=dt,
                fraction_low=0.965,
                fraction_high=0.995,
            )
            for q in targets
        ]
    )
    return _query_dataset_from_pairs(
        kinematics,
        previous,
        targets,
        category="ood_fast_motion",
        trajectory_offset=440_000_000,
    )


def generate_prespecified_ood_points(
    kinematics: KinematicsModel,
    *,
    per_family: int,
    seed: int,
    dt: float = 0.02,
) -> QueryDataset:
    if per_family <= 0:
        raise ValueError("per_family must be positive")
    rng = np.random.default_rng(seed)
    return QueryDataset.concatenate(
        [
            _workspace_sector_queries(
                kinematics, count=per_family, rng=rng, dt=dt
            ),
            _extreme_singular_queries(
                kinematics, count=per_family, rng=rng, dt=dt
            ),
            _extreme_limit_queries(
                kinematics, count=per_family, rng=rng, dt=dt
            ),
            _fast_motion_queries(
                kinematics, count=per_family, rng=rng, dt=dt
            ),
        ]
    )


def _shift_inside_limits(
    kinematics: KinematicsModel, path: np.ndarray
) -> np.ndarray:
    result = np.asarray(path, dtype=np.float64).copy()
    for joint in range(kinematics.nq):
        low = float(np.min(result[:, joint]))
        high = float(np.max(result[:, joint]))
        if low < kinematics.limits.lower[joint]:
            result[:, joint] += kinematics.limits.lower[joint] - low
        if high > kinematics.limits.upper[joint]:
            result[:, joint] -= high - kinematics.limits.upper[joint]
    return np.stack([kinematics.clip(q) for q in result])


def generate_prespecified_ood_trajectories(
    kinematics: KinematicsModel,
    *,
    paths_per_family: int,
    steps: int,
    seed: int,
    dt: float = 0.02,
) -> QueryDataset:
    if paths_per_family <= 0 or steps < 8:
        raise ValueError("OOD trajectories require positive paths and at least eight steps")
    rng = np.random.default_rng(seed)
    previous_rows: list[np.ndarray] = []
    reference_rows: list[np.ndarray] = []
    positions: list[np.ndarray] = []
    rotations: list[np.ndarray] = []
    categories: list[str] = []
    trajectory_ids: list[int] = []
    time_indices: list[int] = []
    trajectory_id = 500_000_000
    phase = np.linspace(0.0, 2.0 * np.pi, steps)
    span = kinematics.limits.upper - kinematics.limits.lower

    for family in OOD_TRAJECTORY_FAMILIES:
        for _ in range(paths_per_family):
            start = kinematics.random_configuration(rng, margin=0.18)
            offsets = np.zeros((steps, kinematics.nq), dtype=np.float64)
            random_phase = rng.uniform(0.0, 2.0 * np.pi, size=kinematics.nq)
            for joint in range(kinematics.nq):
                if family == "ood_trajectory_high_frequency":
                    cycles = 3
                    waveform = np.sin(cycles * phase + random_phase[joint])
                    waveform -= waveform[0]
                else:
                    waveform = (
                        0.65 * np.sin(2 * phase + random_phase[joint])
                        + 0.35 * np.sin(5 * phase + 0.5 * random_phase[joint])
                    )
                    waveform -= waveform[0]
                    cycles = 5
                # Scale from an explicit finite-difference bound rather than a
                # guessed position amplitude.
                unit_step = max(float(np.max(np.abs(np.diff(waveform)))), 1e-12)
                amplitude = min(
                    0.035 * span[joint],
                    0.82 * kinematics.limits.velocity[joint] * dt / unit_step,
                )
                offsets[:, joint] = amplitude * waveform
            reference = _shift_inside_limits(kinematics, start[None, :] + offsets)
            previous = np.vstack([reference[0], reference[:-1]])
            delta = np.stack(
                [
                    np.abs(kinematics.difference(q, p))
                    for q, p in zip(reference, previous, strict=True)
                ]
            )
            if np.any(delta > kinematics.limits.velocity * dt + 1e-9):
                raise RuntimeError(f"generated {family} path exceeds velocity contract")
            poses = [kinematics.forward(q) for q in reference]
            previous_rows.extend(previous)
            reference_rows.extend(reference)
            positions.extend(pose.position for pose in poses)
            rotations.extend(pose.rotation for pose in poses)
            categories.extend([family] * steps)
            trajectory_ids.extend([trajectory_id] * steps)
            time_indices.extend(range(steps))
            trajectory_id += 1

    count = len(previous_rows)
    return QueryDataset(
        previous_q=np.stack(previous_rows),
        target_position=np.stack(positions),
        target_rotation=np.stack(rotations),
        reference_q=np.stack(reference_rows),
        category=np.asarray(categories),
        expected_reachable=np.ones(count, dtype=bool),
        continuity_feasible=np.ones(count, dtype=bool),
        trajectory_id=np.asarray(trajectory_ids, dtype=np.int64),
        time_index=np.asarray(time_indices, dtype=np.int64),
    )


def exact_query_rows(datasets: Iterable[QueryDataset]) -> set[bytes]:
    rows: set[bytes] = set()
    for dataset in datasets:
        numeric = np.ascontiguousarray(
            np.concatenate(
                [
                    dataset.previous_q.reshape(len(dataset), -1),
                    dataset.target_position.reshape(len(dataset), -1),
                    dataset.target_rotation.reshape(len(dataset), -1),
                ],
                axis=1,
            ),
            dtype=np.float64,
        )
        width = numeric.dtype.itemsize * numeric.shape[1]
        rows.update(numeric.view(np.dtype((np.void, width))).reshape(-1).tolist())
    return rows
